# Use a lightweight Python image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt .
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_mapper.txt

# Set the default command
CMD ["python", "experiments_mapper.py"]
